#!/usr/bin/env bash
# generate-index.sh — Build workspace structural index for Explore agent
#
# Generates .claude/index.md — a single structural map of the entire workspace.
# The custom Explore agent (.claude/agents/explore.md) reads this file first,
# answering most questions in 1-3 tool calls instead of 5-15.
#
# Output: .claude/index.md (gitignored, auto-generated, disposable)
# Wired via: SessionStart hook in .claude/settings.json
#
# Usage:
#   generate-index.sh          # Full generation (with freshness gate)
#   generate-index.sh --force  # Skip freshness gate
#
# Cross-platform: works on macOS (BSD stat) and Linux (GNU stat).
# No python3 dependency. Target: < 2 seconds, < 200 lines output.
#
# CUSTOMIZE: This script auto-discovers your workspace structure. You can
# adjust EXCLUDE_DIRS, entry point patterns, and test directory patterns
# to match your projects. The sections are modular — comment out any
# section you don't need.

set -euo pipefail

# ── Resolve workspace root ──

WORKSPACE="${CLAUDE_PROJECT_DIR:-$(cd "$(dirname "$0")/../.." && pwd)}"
INDEX="$WORKSPACE/.claude/index.md"
PLATFORM="$(uname -s)"

# ── Cross-platform helpers ──

file_epoch() {
    if [ "$PLATFORM" = "Darwin" ]; then
        stat -f %m "$1" 2>/dev/null || echo 0
    else
        stat -c %Y "$1" 2>/dev/null || echo 0
    fi
}

now_epoch() {
    date +%s
}

# ── Freshness gate ──
# Skip if: index exists, is < 5 min old, AND git HEAD matches.
# --force bypasses this.

if [ "${1:-}" != "--force" ] && [ -f "$INDEX" ]; then
    index_age=$(( $(now_epoch) - $(file_epoch "$INDEX") ))
    if [ "$index_age" -lt 300 ]; then
        current_hash=$(git -C "$WORKSPACE" rev-parse --short HEAD 2>/dev/null || echo "none")
        index_hash=$(grep -oP '(?<=Commit: `)[a-f0-9]+' "$INDEX" 2>/dev/null | head -1 || echo "stale")
        if [ "$current_hash" = "$index_hash" ]; then
            exit 0  # Index is fresh
        fi
    fi
fi

# ── Exclusion patterns ──
# CUSTOMIZE: Add directories to exclude from tree/find operations
EXCLUDE_DIRS="node_modules|dist|build|.git|venv|__pycache__|.vite|coverage|.next|vendor|.cache|.turbo"

# tree with fallback
tree_dirs() {
    local dir="$1" depth="${2:-2}"
    if command -v tree >/dev/null 2>&1; then
        tree -d -L "$depth" -I "$EXCLUDE_DIRS" --noreport "$dir" 2>/dev/null
    else
        find "$dir" -maxdepth "$depth" -type d \
            -not -path '*/.git/*' -not -path '*/node_modules/*' \
            -not -path '*/dist/*' -not -path '*/build/*' \
            -not -path '*/__pycache__/*' -not -path '*/.cache/*' \
            2>/dev/null | sort | sed "s|^$dir/||" | grep -v '^$' | \
            awk '{ depth=gsub("/","/"); printf "%*s%s\n", depth*2, "", $0 }'
    fi
}

# Extract purpose from shell script comment line 2
script_purpose() {
    sed -n '2s/^# *//p' "$1" 2>/dev/null | sed 's/^[^ ]* — //' | cut -c1-60
}

# Extract single-line frontmatter field (no python3)
frontmatter_field() {
    local file="$1" field="$2"
    sed -n '/^---$/,/^---$/p' "$file" 2>/dev/null | \
        grep "^${field}:" | head -1 | \
        sed "s/^${field}:[[:space:]]*//" | \
        sed "s/^[>|][[:space:]]*//" | \
        sed 's/^["'"'"']//; s/["'"'"']$//' | \
        cut -c1-60
}

# ── Build index ──

TMPFILE=$(mktemp)
trap 'rm -f "$TMPFILE"' EXIT

{
    # ── Header ──
    local_branch=$(git -C "$WORKSPACE" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
    local_hash=$(git -C "$WORKSPACE" rev-parse --short HEAD 2>/dev/null || echo "unknown")
    local_date=$(date '+%Y-%m-%d %H:%M:%S')

    echo "# Workspace Index"
    echo "<!-- Auto-generated by .claude/scripts/generate-index.sh. Do not edit. -->"
    echo ""
    echo "Branch: \`$local_branch\` | Commit: \`$local_hash\` | Generated: $local_date"
    echo ""

    # ── Quick Stats ──
    n_skills=$(find "$WORKSPACE/.claude/skills" -maxdepth 2 -name "SKILL.md" 2>/dev/null | wc -l | tr -d ' ')
    n_agents=$(find "$WORKSPACE/.claude/agents" -maxdepth 1 -name "*.md" ! -name ".gitkeep" 2>/dev/null | wc -l | tr -d ' ')
    n_rules=$(find "$WORKSPACE/.claude/rules" -maxdepth 1 -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
    n_hooks=$(find "$WORKSPACE/.claude/hooks" -maxdepth 1 -name "*.sh" 2>/dev/null | wc -l | tr -d ' ')

    echo "## Quick Stats"
    echo ""
    echo "| Category | Count |"
    echo "|----------|-------|"
    echo "| Skills | $n_skills |"
    echo "| Agents | $n_agents |"
    echo "| Rules | $n_rules |"
    echo "| Hooks | $n_hooks |"

    # Count top-level directories dynamically
    for d in "$WORKSPACE"/*/; do
        [ -d "$d" ] || continue
        dname=$(basename "$d")
        # Skip hidden dirs and common non-project dirs
        case "$dname" in .* | node_modules | dist | build) continue ;; esac
        n=$(find "$d" -maxdepth 1 -mindepth 1 2>/dev/null | wc -l | tr -d ' ')
        echo "| $dname | $n items |"
    done
    echo ""

    # ── Routing Table ──
    echo "## Routing Table"
    echo ""
    echo "| Path | Type | Purpose |"
    echo "|------|------|---------|"

    # Auto-discover top-level directories
    for d in "$WORKSPACE"/*/; do
        [ -d "$d" ] || continue
        dname=$(basename "$d")
        case "$dname" in .* | node_modules | dist | build) continue ;; esac

        purpose=""
        dtype="dir"

        # Check for CLAUDE.md or README for description
        if [ -f "$d/CLAUDE.md" ]; then
            purpose=$(grep -m1 '^# ' "$d/CLAUDE.md" 2>/dev/null | sed 's/^# //' | cut -c1-60)
            dtype="project"
        elif [ -f "$d/README.md" ]; then
            purpose=$(grep -m1 '^# ' "$d/README.md" 2>/dev/null | sed 's/^# //' | cut -c1-60)
            dtype="project"
        fi

        # Check for package.json (code project)
        [ -f "$d/package.json" ] && dtype="project"
        [ -f "$d/requirements.txt" ] && dtype="project"
        [ -f "$d/Dockerfile" ] && dtype="project"

        [ -z "$purpose" ] && purpose="$dname"
        echo "| \`$dname/\` | $dtype | $purpose |"
    done

    # .claude infrastructure
    echo "| \`.claude/skills/\` | infra | $n_skills custom skills |"
    echo "| \`.claude/agents/\` | infra | $n_agents custom agents |"
    echo "| \`.claude/rules/\` | infra | $n_rules rule files |"
    echo "| \`.claude/hooks/\` | infra | $n_hooks hooks |"

    # Key top-level files
    for f in CLAUDE.md README.md Makefile; do
        [ -f "$WORKSPACE/$f" ] && echo "| \`$f\` | config | $(grep -m1 '^# ' "$WORKSPACE/$f" 2>/dev/null | sed 's/^# //' | cut -c1-40 || echo "$f") |"
    done
    echo ""

    # ── Code Projects (auto-discover from any dir with package.json, requirements.txt, etc.) ──
    echo "## Projects"
    echo ""

    for d in "$WORKSPACE"/*/; do
        [ -d "$d" ] || continue
        dname=$(basename "$d")
        case "$dname" in .* | node_modules | dist | build) continue ;; esac

        # Detect stack
        stack=""
        [ -f "$d/package.json" ] && stack="Node/TS"
        [ -f "$d/composer.json" ] && stack="${stack:+$stack + }PHP"
        [ -f "$d/requirements.txt" ] && stack="${stack:+$stack + }Python"
        [ -f "$d/Cargo.toml" ] && stack="${stack:+$stack + }Rust"
        [ -f "$d/go.mod" ] && stack="${stack:+$stack + }Go"
        [ -f "$d/Dockerfile" ] && stack="${stack:+$stack + }Docker"
        [ -z "$stack" ] && continue  # Skip non-project directories

        echo "### $dname"
        echo "- **Stack:** $stack"

        # Entry points
        entries=""
        for f in src/main.tsx src/main.ts src/index.tsx src/index.ts src/main.py main.py app.py index.html api/index.php src/main.rs cmd/main.go Dockerfile; do
            [ -f "$d/$f" ] && entries="${entries:+$entries, }\`$f\`"
        done
        [ -n "$entries" ] && echo "- **Entry:** $entries"

        # Test locations
        tests=""
        for t in src/test tests tests/specs test __tests__ spec; do
            [ -d "$d/$t" ] && tests="${tests:+$tests, }\`$t/\`"
        done
        [ -n "$tests" ] && echo "- **Tests:** $tests"

        # npm scripts
        if [ -f "$d/package.json" ]; then
            scripts=$(sed -n '/"scripts"/,/^\s*}/p' "$d/package.json" 2>/dev/null | \
                grep -v '"scripts"' | \
                grep -oP '^\s+"\K[a-z][a-z:_-]+(?="\s*:)' 2>/dev/null | tr '\n' ', ' | sed 's/,$//' | cut -c1-80)
            [ -n "$scripts" ] && echo "- **Scripts:** $scripts"
        fi

        echo ""
    done

    # ── Infrastructure Summary ──
    echo "## Infrastructure"
    echo ""

    # Skills: names only, comma-separated
    if [ "$n_skills" -gt 0 ]; then
        skill_names=$(find "$WORKSPACE/.claude/skills" -maxdepth 1 -mindepth 1 -type d 2>/dev/null | xargs -I{} basename {} | sort | tr '\n' ', ' | sed 's/,$//')
        echo "**Skills ($n_skills):** $skill_names"
        echo ""
    fi

    # Agents: compact table
    if [ "$n_agents" -gt 0 ]; then
        echo "**Agents ($n_agents):**"
        echo ""
        echo "| Agent | Model |"
        echo "|-------|-------|"
        for a in "$WORKSPACE/.claude/agents/"*.md; do
            [ -f "$a" ] || continue
            aname=$(basename "$a" .md)
            [ "$aname" = ".gitkeep" ] && continue
            amodel=$(frontmatter_field "$a" "model")
            [ -z "$amodel" ] && amodel="default"
            echo "| \`$aname\` | $amodel |"
        done
        echo ""
    fi

    # Rules: names only
    if [ "$n_rules" -gt 0 ]; then
        rule_names=$(find "$WORKSPACE/.claude/rules" -maxdepth 1 -name "*.md" 2>/dev/null | xargs -I{} basename {} .md | sort | tr '\n' ', ' | sed 's/,$//')
        echo "**Rules ($n_rules):** $rule_names"
        echo ""
    fi

    # Hooks: names only
    if [ "$n_hooks" -gt 0 ]; then
        hook_names=$(find "$WORKSPACE/.claude/hooks" -maxdepth 1 -name "*.sh" 2>/dev/null | xargs -I{} basename {} | sort | tr '\n' ', ' | sed 's/,$//')
        echo "**Hooks ($n_hooks):** $hook_names"
        echo ""
    fi

} > "$TMPFILE"

# Atomic write
mv "$TMPFILE" "$INDEX"
trap - EXIT
